
services:
  android-container-1:
    image: budtmo/docker-android:emulator_9.0
    ports:
      - "6080:6080"
      - "5555:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S9
      - WEB_VNC=true
    devices:
      - /dev/kvm
    container_name: android-container-1
    restart: unless-stopped

  android-container-2:
    image: budtmo/docker-android:emulator_9.0
    ports:
      - "6081:6080"
      - "5556:5555"
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true
    devices:
      - /dev/kvm
    container_name: android-container-2
    restart: unless-stopped

  android-container-3:
    image: budtmo/docker-android:emulator_9.0
    ports:
      - "6082:6080"
      - "5557:5555"
    environment:
      - EMULATOR_DEVICE=Nexus 5
      - WEB_VNC=true
    devices:
      - /dev/kvm
    container_name: android-container-3
    restart: unless-stopped
